<a href="https://colab.research.google.com/github/Darshini-A/Social-Network-Analysis/blob/main/PageRank%201%2C2%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1
# Sum of page rank

In [1]:
import numpy as np
import scipy as sc
import pandas as pd
from fractions import Fraction

In [6]:
def display_format (my_vector, my_decimal):
  return np.round ((my_vector).astype(np.float64),
                   decimals = my_decimal)

In [7]:
my_dp = Fraction(1,3)
Mat = np.matrix([[0,0,1],
                 [Fraction(1,2),0,0],
                 [Fraction(1,2),1,0]])

Ex = np.zeros((3,3))
Ex[:] = my_dp
beta = 0.7
AI = beta * Mat + ((1-beta) * Ex)
r = np.matrix([my_dp, my_dp, my_dp])
r = np.transpose(r)
previous_r = r

In [8]:
for i in range(1,100):
  r = AI * r
  print(display_format(r, 3))
  if (previous_r == r).all():
    break
    previous_r = r

print("Final : \n", display_format(r, 3))
print("Sum", np.sum(r))

[[0.333]
 [0.217]
 [0.45 ]]
[[0.415]
 [0.217]
 [0.368]]
[[0.358]
 [0.245]
 [0.397]]
[[0.378]
 [0.225]
 [0.397]]
[[0.378]
 [0.232]
 [0.39 ]]
[[0.373]
 [0.232]
 [0.395]]
[[0.376]
 [0.231]
 [0.393]]
[[0.375]
 [0.232]
 [0.393]]
[[0.375]
 [0.231]
 [0.394]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [

In [ ]:
# 2
# Page rank

In [9]:
def win(matrix, m, o):
	k = 0
	for i in range(0, n):
		if(int(matrix[i][m]) == 1):
			k = k+1
	l = 0
	for i in range(0, n):
		if(int(matrix[o][i] == 1)):
			for j in range(0, n):
				if(matrix[j][i] == 1):
					l = l+1
	return float(k/l)


def wout(matrix, m, o):
	k = 0
	for i in range(0, n):
		if(int(matrix[0][i]) == 1):
			k = k+1
	l = 0
	for i in range(0, n):
		if(int(matrix[o][i] == 1)):
			for j in range(0, n):
				if(matrix[i][j] == 1):
					l = l+1
	return float(k/l)


def pagerank(matrix, o, n, p):
	a = 0
	for i in range(0, n):
		if(int(matrix[i][o]) == 1):
			k = 0
			for s in range(0, n):
				if(matrix[i][s] == 1):
					k = k+1
			a = a+float((p[i]/k)*win(matrix, i, o)*wout(matrix, i, o))
	return a

In [10]:
n = 5
matrix = [[0, 1, 1, 1, 0], [1, 0, 1, 1, 0], [
	0, 0, 0, 1, 0], [0, 0, 1, 0, 1], [0, 1, 1, 1, 0]]
d = 0.25 # damping factor

o = 5
print("Number of iterations :", o)

sum = 0
p = []

for i in range(0, n):
	p.append(1)
for k in range(0, o):
	for u in range(0, n):
		g = pagerank(matrix, u, n, p)
		p[u] = (1-d)+d*g
for i in range(0, n):
	sum += p[i]
	print("Page rank of node ", i+1, " : ", p[i])
print("Sum of all page ranks : ", sum)

Number of iterations : 5
Page rank of node  1  :  0.7563090216610497
Page rank of node  2  :  0.7570825988098917
Page rank of node  3  :  1.021617613959075
Page rank of node  4  :  0.9412927238508162
Page rank of node  5  :  0.7735323180962704
Sum of all page ranks :  4.249834276377103
